name: Check and Update Sogou Dict

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '10 0 * * SUN'

jobs:
  check_update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install requests

    - name: Download Sogou Popular Dict
      run: |
        LATEST_TAG=$(curl -s https://api.github.com/repos/studyzy/imewlconverter/releases/latest | jq -r .tag_name)
        wget -P /tmp "https://github.com/studyzy/imewlconverter/releases/download/${LATEST_TAG}/imewlconverter_Linux.tar.gz"
        mkdir -p /tmp/imewlconverter
        tar -xvf /tmp/imewlconverter_Linux.tar.gz -C /tmp/imewlconverter
        python3 others/script/python/Scel2Rime.py
        mv sogou_popular.dict.yaml ext_dicts/sogou_popular.dict.yaml
        python3 others/script/python/MergeDict.py cn_dicts/ext.dict.yaml cn_dicts/base.dict.yaml ext_dicts/base.dict.yaml
        python3 others/script/python/ReDict.py ext_dicts/base.dict.yaml ext_dicts/wiki_dict.dict.yaml ext_dicts/wiki_dict.dict.yaml
        python3 others/script/python/ReDict.py ext_dicts/base.dict.yaml ext_dicts/sogou_total_dict.official.dict.yaml ext_dicts/sogou_total_dict.official.dict.yaml
        python3 others/script/python/ReDict.py ext_dicts/base.dict.yaml ext_dicts/sogou_total_dict.unofficial.dict.yaml ext_dicts/sogou_total_dict.unofficial.dict.yaml
        python3 others/script/python/ReDict.py ext_dicts/base.dict.yaml ext_dicts/sogou_popular.dict.yaml ext_dicts/sogou_popular.dict.yaml
        python3 others/script/python/ReDict.py ext_dicts/sogou_total_dict.official.dict.yaml ext_dicts/sogou_popular.dict.yaml ext_dicts/sogou_popular.dict.yaml
        python3 others/script/python/ReDict.py ext_dicts/sogou_total_dict.unofficial.dict.yaml ext_dicts/sogou_popular.dict.yaml ext_dicts/sogou_popular.dict.yaml
        rm -f sogou_popular.scel ext_dicts/base.dict.yaml

    - name: Check for changes and push updates
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        if git diff-index --quiet --cached HEAD --ignore-submodules --; then
          echo "Error: Only whitespace changes detected. No changes to commit."
        else
          git diff --quiet && git diff --staged --quiet || git commit -a -m "Update Sogou Dict" && git push
        fi
